"""Database creation

Revision ID: 8adb3edfc5a1
Revises: 
Create Date: 2023-11-05 22:47:03.501831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8adb3edfc5a1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.String(), nullable=False),
        sa.Column('image', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workouts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approaches',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('eid', sa.Integer(), nullable=True),
        sa.Column('wid', sa.Integer(), nullable=True),
        sa.Column('reps', sa.Integer(), nullable=True),
        sa.Column('weight', sa.Integer(), nullable=True),
        sa.Column('time', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['eid'], ['exercises.id'], ),
        sa.ForeignKeyConstraint(['wid'], ['workouts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stats',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('wid', sa.Integer(), nullable=True),
        sa.Column('record_weight', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['wid'], ['workouts.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.drop_table('approaches')
    op.drop_table('workouts')
    op.drop_table('users')
    op.drop_table('exercises')
    # ### end Alembic commands ###
